# Generated by Django 6.1 on 2026-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_project_category_remove_project_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=255),
        ),
    ]
