# Generated by Django 6.1 on 2026-09-16 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('it', 'IT'), ('non-it', 'Non-IT')], default='it', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
