# Generated by Django 6.1 on 2026-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_category_project_ended_at_project_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='education_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='education',
            name='education_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
